apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flask-blog
  labels:
    app: flask-blog
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-blog
  template:
    metadata:
      labels:
        app: flask-blog
    spec:
      containers:
      - name: flask-blog
        image: manches300/flask-blog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        envFrom:
        - secretRef:
            name: flask-blog-secrets
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
             path: /
             port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"